name: D4L Crypto RSA PSS CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  validation:
    runs-on: macos-latest

    concurrency:
      group: build-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
    - name: Display runner context
      run: hostname -s
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Reset iOS simulators (Required to avoid tests failing problem)
      run: xcrun simctl erase all
    - name: test iOS
      run: |
           swift package generate-xcodeproj 
           xcodebuild -scheme Data4LifeCryptoRSAPSS-Package -derivedDataPath build test
    - name: test macOS
      run: swift test
    - name: Install sonar scanner
      run: brew install sonar-scanner
    - name: Create sonarqube report
      run: |
           xcrun llvm-profdata merge build/Build/ProfileData/*/*.profdata -output merged.profdata
           xcrun --run llvm-cov show build/Build/Products/Debug/Data4LifeCryptoRSAPSS.framework/Data4LifeCryptoRSAPSS --instr-profile merged.profdata >> sonarqube-swift-coverage
    - name: SonarCloud PR Scan
      if: github.event_name == 'pull_request'
      run: sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.pullrequest.base=$GITHUB_BASE_REF -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.provider=GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: SonarCloud Push Scan
      if: github.event_name == 'push'
      run: sonar-scanner -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
